apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app-container
    image: 1139675527364.dkr.ecr.us-east-1.amazonaws.com/k8s-assignment:app  # Replace with your image repository and image name
    env:
    - name: DBHOST
      value: mysql-service  # Replace with the hostname of your MySQL service
    - name: DBUSER
      value: root
    - name: DBPWD
      value: password  # Replace with your MySQL password
    - name: DATABASE
      value: employees  # Replace with your MySQL database name
    - name: APP_COLOR
      value: lime  # Replace with the desired color
    ports:
    - containerPort: 8080
    
