apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: 139675527364.dkr.ecr.us-east-1.amazonaws.com/k8s-assignment:mysql
      env:
          - name: MYSQL_ROOT_PASSWORD
            value: password  # Replace with your desired MySQL root password
          - name: MYSQL_DATABASE
            value: employees
      ports:
        - containerPort: 3306
       
